name: Rust API Deployment

on:
  push:
    branches:
      - master  # Adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Build
        run: cargo +nightly build --release
      - name: deploy
        run: cargo +nightly run